### ISSUE TITLE
ItemLoseDurabilityEvent is cancelled, item durability still goes down

### ISSUE THREAD

**Issue by Zeryther** [Eniripsa96/MCCore#2]
I cancelled the ItemLoseDurabilityEvent but the item still loses durability

**Comment by Zeryther** [comment]
(durability-enabled is true in the config)

**Comment by Eniripsa96** [comment]
The option is just for whether or not MCCore tracks durability for launching the event. It is not supposed to fully control the durability loss.

**Comment by Eniripsa96** [comment]
Looking back on this, not sure what I was thinking with that response. Fixing this for v1.46.
